# Config shared by all jobs
defaults: &defaults
  working_directory: /tmp/xiva-client
  docker:
    - image: circleci/node:10

version: 2
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: /tmp
          paths:
            - xiva-client/*

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Lint
          command: yarn lint --format junit -o reports/eslint/results.xml
      - store_test_results:
          path: reports

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Tests
          command: yarn test --ci --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: reports/jest/results.xml
      - store_test_results:
          path: reports

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Run build
          command: CI=false yarn build
      - persist_to_workspace:
          root: /tmp
          paths:
            - xiva-client/build/*

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Upload build
          command: scp -4 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r build/* $SSH_USER@$SSH_HOST:${DEPLOY_FOLDER}client/deploy-cache
      - run:
          name: Run deploy script
          command: ssh -4 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SSH_HOST "cd ${DEPLOY_FOLDER}client && ./deploy.sh $CIRCLE_SHA1"
      - run:
          name: Success webhook
          command: |
            chmod +x .circleci/success.sh
            ./.circleci/success.sh
      - run:
          name: Failure webhook
          command: |
            chmod +x .circleci/fail.sh
            ./.circleci/fail.sh
          when: on_fail

workflows:
  version: 2
  flow:
    jobs:
      - setup:
          filters:
            branches:
              ignore: i18n-master
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
